### ISSUE TITLE
iVysílání - problém s video varováním

### ISSUE THREAD

**Issue by ToKroCZ** [lzoubek/xbmc-doplnky#297]
U několika dílů různých pořadů je před samotným obsahem video varování, že tento pořad není vhodný pro děti. Například Pološero či Kmeny. U těchto dílů se přehraje pouze toto několika sekundové video, ale už se nepustí samotný obsah.

OT: Dal jsem to i do Issues toho doplňku přímo u StepanOrt. Nevím kam to správně patří. Tady jsou všechny Issues, ale zase logicky bych to dal spíš přímo vývojáři...

**Comment by lgreg** [comment]
Zkousel sem to a myslim, ze uz je to v poradku. Muzes to prosim vyzkouset a pripadne, pokud by ten problem pretrvaval napsat konkretni dil, ktery ti nefuguje?

**Comment by ToKroCZ** [comment]
Ahoj,
už je to fixnuté. Funguje to tak, jak má. Díky ;)

po 27. 4. 2015 v 13:58 odesílatel lgreg <notifications@github.com> napsal:
