### ISSUE TITLE
Sosac.ph - nefunkční písmena

### ISSUE THREAD

**Issue by ToKroCZ** [lzoubek/xbmc-doplnky#320]
Po zvolení S nebo P v sekci Movies Kodi jen donekonečna ukazuje "Pracuji". Jiná písmena funkční.

**Comment by petrm74** [comment]
Mě to funguje, pouze to chvíli trvá.

**Comment by ToKroCZ** [comment]
Trvá to hodně dlouho, ale pak se to načte. Asi se jednalo o výpadek webu.
