### ISSUE TITLE
Sosac add-on - add all to library - načítá pouze 173 filmů

### ISSUE THREAD

**Issue by vbrenek** [lzoubek/xbmc-doplnky#321]
Při přidávání filmů do Kodi knihovny načetl systém pouze 161 filmů (na první pokus) a na druhý pouze 173. Stalo se to i dalším 2 lidem ve stejnou dobu. Jedná se o chybu doplňku nebo dělám něco špatně?

**Comment by petrm74** [comment]
Myslíš do knihovny, nebo do souborů?

**Comment by vbrenek** [comment]
Do souboru... Tedy vytvoří jen 173 .strm souboru. U seriálu je to v poradku a nactou se všechny. 

Odesláno z aplikace Outlook Mobile




On Sun, Jan 3, 2016 at 12:44 PM -0800, "Petr M" <notifications@github.com> wrote:












Myslíš do knihovny, nebo do souborů?

**Comment by Scorpio256** [comment]
Je v tom nějaká novinka? Také mi to načte cca 180 filmů a konec. Zkoušel jsem i starší verzi (1.2.3) a stejné.

**Comment by petrm74** [comment]
Zkus verzi 1.2.5c - https://github.com/kodi-czsk/plugin.video.sosac.ph/pull/44
